### ISSUE TITLE
Question about adding new accounts

### ISSUE THREAD

**Issue by ChronoBrake** [KaluNight/Zoe-Discord-Bot#324]
Hey, i have quick question. I really like in other bot function "verification by client code". Your bot be better, but missing that function hurt. You using it in ban function, but no for adding new accounts. I understand when account be added by admin, but when we wanna turn adding for all users on server by >register command it's be really nice to have that verify option here.
Best regards

**Comment by KaluNight** [comment]
Hello @ChronoBrake !

By coincidence, I recently came up with an option that would do exactly what you want.

Indeed, adding this feature would be very interesting for large Discord servers who would like to make sure that linked accounts belong to the owner of a Discord account.

This is how i see the feature:
-Will be an option disable by default.
-Can be used only if the option "Everyone can add himself inside the bot" is enable.
-Admins can link accounts without verification. (with all commands, not only register)

If you have any feedback with how i imagine it please tell me.

Since this option is really connected with another already planned feature _New option to have roles by rank (silver player -> receive silver role)_ i plan to add it at the same time. 

For more information, join the official Zoe Discord Server : https://discord.gg/8aXPpwUTKe (check channel _#dev-status_ **V1.11.0**)

Have a great day!

**Comment by KaluNight** [comment]
Hello @ChronoBrake !

This feature will be live today or tomorrow (#370) in early access for supporter users (in 2 week for everyone), since you are the guy who suggested it i can give you an access. (more info in the patch)

If you have any question send me a DM on discord

**Comment by KaluNight** [comment]
Closed since feature is now live.
